//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MundaneWebAPI.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int itemid { get; set; }
        public string name { get; set; }
        public string worth { get; set; }
        public string description { get; set; }
        public bool bmagical { get; set; }
        public bool bfood { get; set; }
        public bool bequipment { get; set; }
        public bool btool { get; set; }
        public bool bpotion { get; set; }
        public bool btradegood { get; set; }
        public int rarity { get; set; }
    }
}
